version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-spring-security
    environment:
      POSTGRES_DB: spring-security
      POSTGRES_USER: security-user
      POSTGRES_PASSWORD: secure-password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

