spring:
  security:
    oauth2:
      resourceserver:
        issuers:
          google:
            issuer-uri: https://accounts.google.com
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
          meta:
            issuer-uri: https://www.facebook.com
            jwk-set-uri: https://www.facebook.com/.well-known/oauth/facebook-security/prof


  datasource:
    url: jdbc:postgresql://localhost:5432/spring-security
    username:
    password:
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  auth:
    google:
      client-id: your-google-client-id
    meta:
      client-id: your-meta-client-id
    debater:
      secret-key: "somekey"
